// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentController from "./comment_controller.js"
application.register("comment", CommentController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import PostController from "./post_controller.js"
application.register("post", PostController)
