require:
  - rubocop-performance
  - rubocop-rails
#   - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/**/*"

Rails/I18nLocaleTexts:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*"

Metrics/AbcSize:
  Enabled: false
