default: &default
  adapter: sqlite3
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sqlite/reddit_development.db

test:
  <<: *default
  database: sqlite/reddit_test.db

production:
  url: <%= ENV["DATABASE_URL"] %>
