# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ActionText::ContentHelper; end
module ActionText::TagHelper; end
module RDoc::Task; end
module Turbo::Streams::ActionHelper; end
