# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::PreviewHelper; end
module RDoc::Task; end
module Turbo::Streams::ActionHelper; end
